#!/usr/bin/env python3
"""Emit a Google Apps Script that builds the peer-eval form.

Reads roster.json (produced by fetch_roster.py) and writes build_form.gs.
Paste the contents of build_form.gs into a new Apps Script project at
https://script.google.com (signed in with your UW account), then run
buildForm(). The form URL is logged to the execution transcript.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# 5-point Likert rubric. Each item: (short id used in question title, help text).
RUBRIC_LIKERT = [
    ("Technical Contribution", "Did the member contribute a fair share of the codebase or technical research?"),
    ("Reliability",            "Did the member meet internal milestones and attend group meetings?"),
    ("Communication",          "Did the member respond promptly to messages and collaborate effectively on the repository?"),
    ("Problem Solving",        "Did the member help resolve blockers and contribute to the AI implementation strategy?"),
]

LIKERT_LABELS = [
    "1 - Poor",
    "2 - Below expectations",
    "3 - Meets expectations",
    "4 - Exceeds expectations",
    "5 - Outstanding",
]

RUBRIC_TEXT = [
    "Strengths",
    "Areas for improvement",
]

DEFAULT_TITLE = "DYOP Peer & Self Evaluation"
DEFAULT_DESCRIPTION = (
    "Confidential peer and self evaluation. Pick your group on the next page, "
    "then rate every member of your team (including yourself) on each dimension. "
    "Your responses are visible only to course staff."
)


def emit(roster: list[dict], title: str, description: str) -> str:
    payload = {
        "title": title,
        "description": description,
        "likert_labels": LIKERT_LABELS,
        "likert_items": [{"id": k, "help": v} for k, v in RUBRIC_LIKERT],
        "text_items": RUBRIC_TEXT,
        "groups": [
            {
                "name": g["group"],
                "members": [m["name"] for m in g["members"] if m.get("name")],
            }
            for g in roster
            if g.get("members")
        ],
    }
    cfg_json = json.dumps(payload, indent=2, ensure_ascii=False)
    return _SCRIPT_TEMPLATE.replace("__CONFIG_JSON__", cfg_json)


_SCRIPT_TEMPLATE = r"""// Auto-generated by generate_apps_script.py. Do not hand-edit.
// Paste into a new project at https://script.google.com (signed in with your
// UW Google account), then Run > buildForm. The form URL is logged to the
// execution transcript (View > Logs).

const CONFIG = __CONFIG_JSON__;

function buildForm() {
  const form = FormApp.create(CONFIG.title)
    .setDescription(CONFIG.description)
    .setCollectEmail(true)
    .setRequireLogin(true)
    .setProgressBar(true)
    .setAllowResponseEdits(false)
    .setLimitOneResponsePerUser(true);

  // Page 1: pick your group. Routes to that group's section via page navigation.
  const groupItem = form.addMultipleChoiceItem()
    .setTitle('Which group are you in?')
    .setRequired(true);

  const pages = [];
  CONFIG.groups.forEach(function (g) {
    const page = form.addPageBreakItem()
      .setTitle(g.name)
      .setHelpText('Rate every member of your team (including yourself) on each dimension.');
    page.setGoToPage(FormApp.PageNavigationType.SUBMIT);
    pages.push({ name: g.name, page: page });

    g.members.forEach(function (memberName) {
      form.addSectionHeaderItem()
        .setTitle('Evaluating: ' + memberName)
        .setHelpText('If this is you, rate yourself honestly.');

      CONFIG.likert_items.forEach(function (item) {
        form.addMultipleChoiceItem()
          .setTitle(memberName + ' — ' + item.id)
          .setHelpText(item.help)
          .setChoiceValues(CONFIG.likert_labels)
          .setRequired(true);
      });

      CONFIG.text_items.forEach(function (q) {
        form.addParagraphTextItem()
          .setTitle(memberName + ' — ' + q)
          .setRequired(false);
      });
    });
  });

  groupItem.setChoices(pages.map(function (p) {
    return groupItem.createChoice(p.name, p.page);
  }));

  Logger.log('Form (live URL): ' + form.getPublishedUrl());
  Logger.log('Form (short URL): ' + form.shortenFormUrl(form.getPublishedUrl()));
  Logger.log('Edit URL: ' + form.getEditUrl());
}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--roster", type=Path, default=Path("roster.json"))
    ap.add_argument("--output", type=Path, default=Path("build_form.gs"))
    ap.add_argument("--title", default=DEFAULT_TITLE)
    ap.add_argument("--description", default=DEFAULT_DESCRIPTION)
    args = ap.parse_args()

    if not args.roster.exists():
        print(f"roster file not found: {args.roster} (run fetch_roster.py first)", file=sys.stderr)
        return 2
    roster = json.loads(args.roster.read_text())
    if not roster:
        print("roster is empty", file=sys.stderr)
        return 2

    args.output.write_text(emit(roster, args.title, args.description))
    n_groups = len(roster)
    n_students = sum(len(g["members"]) for g in roster)
    print(f"wrote {args.output}: {n_groups} groups, {n_students} students")
    print()
    print("Next steps:")
    print("  1. Open https://script.google.com (signed in as pisan@uw.edu)")
    print("  2. New project. Replace Code.gs with the contents of " + str(args.output))
    print("  3. Run > buildForm. Approve the OAuth prompt the first time.")
    print("  4. View > Logs (or Executions) to get the form URL.")
    print("  5. Share the form URL via Canvas. It is restricted to uw.edu sign-in.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
