#!/usr/bin/env python3
"""Emit a Google Apps Script that builds the peer-eval form.

Reads roster.json (produced by fetch_roster.py) and writes build_form.gs.
Paste the contents of build_form.gs into a new Apps Script project at
https://script.google.com (signed in with your UW account), then run
buildForm(). The form URL is logged to the execution transcript.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# 5-point Likert rubric. Each item: (short id used in question title, help text).
RUBRIC_LIKERT = [
    ("Technical Contribution", "Did the member contribute a fair share of the codebase or technical research?"),
    ("Reliability",            "Did the member meet internal milestones and attend group meetings?"),
    ("Communication",          "Did the member respond promptly to messages and collaborate effectively on the repository?"),
    ("Problem Solving",        "Did the member help resolve blockers and contribute to the AI implementation strategy?"),
]

LIKERT_LABELS = [
    "1 - Poor",
    "2 - Below expectations",
    "3 - Meets expectations",
    "4 - Exceeds expectations",
    "5 - Outstanding",
]

RUBRIC_TEXT = [
    "Strengths",
    "Areas for improvement",
]

DEFAULT_TITLE = "DYOP Peer & Self Evaluation"
DEFAULT_DESCRIPTION = (
    "Confidential peer and self evaluation. Pick your group on the next page, "
    "then rate every member of your team (including yourself) on each dimension. "
    "Your responses are visible only to course staff."
)


def emit(roster: list[dict], title: str, description: str) -> str:
    payload = {
        "title": title,
        "description": description,
        "likert_labels": LIKERT_LABELS,
        "likert_items": [{"id": k, "help": v} for k, v in RUBRIC_LIKERT],
        "text_items": RUBRIC_TEXT,
        "groups": [
            {
                "name": g["group"],
                "members": [m["name"] for m in g["members"] if m.get("name")],
            }
            for g in roster
            if g.get("members")
        ],
    }
    cfg_json = json.dumps(payload, indent=2, ensure_ascii=False)
    return _SCRIPT_TEMPLATE.replace("__CONFIG_JSON__", cfg_json)


_SCRIPT_TEMPLATE = r"""// Auto-generated by generate_apps_script.py. Do not hand-edit.
// Paste into a new project at https://script.google.com (signed in with your
// UW Google account), then Run > buildForm. The form URL is logged to the
// execution transcript (View > Executions, or Ctrl/Cmd+Enter).

const CONFIG = __CONFIG_JSON__;

// IMPORTANT: console.log streams live to the Executions panel; Logger.log
// is buffered until the script ENDS, so it shows nothing on cancel/timeout.
// All progress here uses console.log so you can watch it in real time.
function buildForm() {
  const t0 = Date.now();
  const totalGroups = CONFIG.groups.length;
  const totalMembers = CONFIG.groups.reduce(function (n, g) { return n + g.members.length; }, 0);
  const itemsPerMember = 1 + CONFIG.text_items.length; // 1 grid + N paragraph items
  const estItems = 1 + totalGroups + totalMembers * itemsPerMember;
  console.log('buildForm: ' + totalGroups + ' groups, ' + totalMembers +
              ' students, ~' + estItems + ' items to create');

  const form = FormApp.create(CONFIG.title)
    .setDescription(CONFIG.description)
    .setCollectEmail(true)
    .setRequireLogin(true)
    .setLimitOneResponsePerUser(true);
  console.log('  form created: ' + form.getEditUrl() + '  (+' + secs(t0) + 's)');

  // Page 1: pick your group. Routes to that group's section via page navigation.
  const groupItem = form.addMultipleChoiceItem()
    .setTitle('Which group are you in?')
    .setRequired(true);
  console.log('  group-selector item added  (+' + secs(t0) + 's)');

  const gridHelp = CONFIG.likert_items
    .map(function (item) { return item.id + ': ' + item.help; })
    .join('\n');
  const rubricRows = CONFIG.likert_items.map(function (item) { return item.id; });

  const pages = [];
  let memberCount = 0;
  CONFIG.groups.forEach(function (g, gi) {
    console.log('[group ' + (gi + 1) + '/' + totalGroups + '] ' + g.name +
                ' (' + g.members.length + ' members)  (+' + secs(t0) + 's)');

    const page = form.addPageBreakItem()
      .setTitle(g.name)
      .setHelpText('Rate every member of your team (including yourself).');
    page.setGoToPage(FormApp.PageNavigationType.SUBMIT);
    pages.push({ name: g.name, page: page });

    // Rewire the group dropdown after every page so a cancelled run still
    // leaves a functional (if partial) form behind.
    groupItem.setChoices(pages.map(function (p) {
      return groupItem.createChoice(p.name, p.page);
    }));

    g.members.forEach(function (memberName, mi) {
      memberCount++;
      console.log('  [' + memberCount + '/' + totalMembers + '] ' +
                  g.name + ' :: ' + memberName + '  (+' + secs(t0) + 's)');

      // One rating table per member: rubric dimensions × 1-5 Likert.
      form.addGridItem()
        .setTitle('Evaluating: ' + memberName)
        .setHelpText(gridHelp)
        .setRows(rubricRows)
        .setColumns(CONFIG.likert_labels)
        .setRequired(true);

      CONFIG.text_items.forEach(function (q) {
        form.addParagraphTextItem()
          .setTitle(memberName + ' — ' + q)
          .setRequired(false);
      });
    });
  });

  console.log('DONE in ' + secs(t0) + 's');
  console.log('Form (live URL): ' + form.getPublishedUrl());
  console.log('Edit URL: ' + form.getEditUrl());
}

function secs(t0) { return ((Date.now() - t0) / 1000).toFixed(1); }
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--roster", type=Path, default=Path("roster.json"))
    ap.add_argument("--output", type=Path, default=Path("build_form.gs"))
    ap.add_argument("--title", default=DEFAULT_TITLE)
    ap.add_argument("--description", default=DEFAULT_DESCRIPTION)
    args = ap.parse_args()

    if not args.roster.exists():
        print(f"roster file not found: {args.roster} (run fetch_roster.py first)", file=sys.stderr)
        return 2
    # strict=False tolerates any control chars that snuck into older roster files
    # (Canvas sometimes returns group names with embedded tabs).
    roster = json.loads(args.roster.read_text(), strict=False)
    if not roster:
        print("roster is empty", file=sys.stderr)
        return 2

    args.output.write_text(emit(roster, args.title, args.description))
    n_groups = len(roster)
    n_students = sum(len(g["members"]) for g in roster)
    print(f"wrote {args.output}: {n_groups} groups, {n_students} students")
    print()
    print("Next steps:")
    print("  1. Open https://script.google.com (signed in as pisan@uw.edu)")
    print("  2. New project. Replace Code.gs with the contents of " + str(args.output))
    print("  3. Run > buildForm. Approve the OAuth prompt the first time.")
    print("  4. View > Logs (or Executions) to get the form URL.")
    print("  5. Share the form URL via Canvas. It is restricted to uw.edu sign-in.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
